# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-17 00:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagerProfile',
            fields=[
                ('profile_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('camera_type', models.CharField(blank=True, max_length=128, verbose_name='camera type')),
                ('address', models.CharField(blank=True, max_length=128, verbose_name='address')),
                ('website', models.URLField(blank=True, verbose_name='website')),
                ('photography_type', models.CharField(blank=True, max_length=128, verbose_name='photography type')),
                ('facebook', models.URLField(blank=True, verbose_name='facebook')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
